services:
  - type: web
    name: inventario-django
    env: python
    plan: free
    region: oregon
    buildCommand: ./build.sh
    startCommand: gunicorn proyecto_config.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: inventario-db
          property: connectionString

databases:
  - name: inventario-db
    plan: free
