# Generated by Django 4.2.24 on 2025-10-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_proyecto', '0002_proveedor_contacto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialmovimiento',
            options={'ordering': ['-fecha_movimiento']},
        ),
        migrations.AlterField(
            model_name='historialmovimiento',
            name='tipo_movimiento',
            field=models.CharField(choices=[('CREACION', 'Creación'), ('EDICION', 'Edición'), ('ELIMINACION', 'Eliminación')], max_length=20),
        ),
    ]
