# Generated by Django 4.2.24 on 2025-10-13 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mi_proyecto', '0003_alter_historialmovimiento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidaproducto',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mi_proyecto.productos'),
        ),
    ]
