# Generated by Django 4.2.24 on 2025-10-13 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mi_proyecto', '0004_alter_salidaproducto_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidaproducto',
            name='producto',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='mi_proyecto.productos'),
            preserve_default=False,
        ),
    ]
