# Generated by Django 4.2.24 on 2025-10-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_proyecto', '0005_alter_salidaproducto_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
