# Generated by Django 4.2.24 on 2025-10-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_proyecto', '0006_productos_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialmovimiento',
            name='tipo_movimiento',
            field=models.CharField(choices=[('CREACION', 'Creación'), ('EDICION', 'Edición'), ('ELIMINACION', 'Eliminación'), ('SALIDA', 'Salida'), ('DESHABILITACION', 'Deshabilitación')], max_length=20),
        ),
    ]
